In [55]:
import pandas as pd
events=pd.read_csv("../RAW_DATA/event.csv")
customers=pd.read_csv("../RAW_DATA/customers.csv")
products=pd.read_csv("../RAW_DATA/products.csv")
transactions=pd.read_csv("../RAW_DATA/transactions.csv")
campaigns=pd.read_csv("../RAW_DATA/campaigns.csv")

C:\Users\acer\AppData\Local\Temp\ipykernel_13508\3962827700.py:2: DtypeWarning: Columns (1,4,6,7,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  events=pd.read_csv("../RAW_DATA/event.csv")
C:\Users\acer\AppData\Local\Temp\ipykernel_13508\3962827700.py:5: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions=pd.read_csv("../RAW_DATA/transactions.csv")

In [56]:
customers.head()

,customer_id,signup_date,country,age,gender,loyalty_tier,acquisition_channel
0,1.0,4/8/2021,BR,48.0,Male,Bronze,Referral
1,2.0,4/28/2023,IN,36.0,Female,Silver,Organic
2,3.0,12/18/2022,UK,35.0,Female,Silver,Organic
3,4.0,4/26/2022,US,45.0,Male,Silver,Paid Search
4,5.0,4/20/2022,IN,53.0,Male,Silver,Organic

In [57]:
customers.info()
customers.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          51390 non-null  float64
 1   signup_date          51390 non-null  object
 2   country              51390 non-null  object
 3   age                  51390 non-null  float64
 4   gender               51390 non-null  object
 5   loyalty_tier         51390 non-null  object
 6   acquisition_channel  51390 non-null  object
dtypes: float64(2), object(5)
memory usage: 5.3+ MB

customer_id            48610
signup_date            48610
country                48610
age                    48610
gender                 48610
loyalty_tier           48610
acquisition_channel    48610
dtype: int64

In [58]:
customers = customers.drop_duplicates()

In [59]:
customers[customers.duplicated()]

Empty DataFrame
Columns: [customer_id, signup_date, country, age, gender, loyalty_tier, acquisition_channel]
Index: []

In [60]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [61]:
products.head()

   product_id     category     brand  base_price launch_date  is_premium
0           1      Grocery  Brand_58       14.19  2021-08-02           0
1           2      Fashion   Brand_1       25.80  2021-09-14           0
2           3  Electronics  Brand_70      165.46  2021-01-18           1
3           4      Fashion  Brand_56       75.45  2023-03-03           1
4           5       Sports   Brand_1       72.50  2022-04-19           1

In [62]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   object
 2   brand        2000 non-null   object
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   object
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 93.9+ KB

In [63]:
products.isnull().sum()

product_id     0
category       0
brand          0
base_price     0
launch_date    0
is_premium     0
dtype: int64

In [64]:
products[products.duplicated()]

Empty DataFrame
Columns: [product_id, category, brand, base_price, launch_date, is_premium]
Index: []

In [65]:
products['launch_date']=pd.to_datetime(products['launch_date'])

In [66]:
campaigns.head()

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144

In [67]:
campaigns.info()
campaigns.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      50 non-null     int64
 1   channel          50 non-null     object
 2   objective        50 non-null     object
 3   start_date       50 non-null     object
 4   end_date         50 non-null     object
 5   target_segment   50 non-null     object
 6   expected_uplift  50 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ KB

campaign_id        0
channel            0
objective          0
start_date         0
end_date           0
target_segment     0
expected_uplift    0
dtype: int64

In [68]:
campaigns[campaigns.duplicated()]

Empty DataFrame
Columns: [campaign_id, channel, objective, start_date, end_date, target_segment, expected_uplift]
Index: []

In [69]:
campaigns['start_date']=pd.to_datetime(campaigns['start_date'])
campaigns['end_date']=pd.to_datetime(campaigns['end_date'])

In [70]:
campaigns['campaign_duration_days'] = (
    campaigns['end_date'] - campaigns['start_date']
).dt.days

In [71]:
transactions.head()

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
0,80820.0,1/30/2021 6:32,2.0,1802.0,1.0,0.05,60.09,0.0,0.0
1,11222.0,11/19/2023 7:55,8.0,1794.0,1.0,0.15,65.25,26.0,0.0
2,82273.0,4/6/2022 23:00,9.0,1970.0,1.0,0.10,65.63,29.0,0.0
3,24209.0,8/31/2022 8:52,13.0,NaN,3.0,0.05,NaN,50.0,0.0
4,63602.0,12/1/2021 12:53,13.0,1715.0,1.0,0.00,71.90,17.0,0.0

In [72]:
transactions.info()
transactions.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103127 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    53095 non-null  float64
 1   timestamp         53095 non-null  object
 2   customer_id       53095 non-null  float64
 3   product_id        47791 non-null  float64
 4   quantity          53095 non-null  float64
 5   discount_applied  53095 non-null  float64
 6   gross_revenue     47791 non-null  float64
 7   campaign_id       53095 non-null  float64
 8   refund_flag       53095 non-null  float64
dtypes: float64(8), object(1)
memory usage: 7.1+ MB

transaction_id      50032
timestamp           50032
customer_id         50032
product_id          55336
quantity            50032
discount_applied    50032
gross_revenue       55336
campaign_id         50032
refund_flag         50032
dtype: int64

In [73]:
transactions['timestamp']=pd.to_datetime(transactions['timestamp'])

In [74]:
transactions = transactions.dropna(subset=['product_id'])

In [75]:
transactions[transactions.duplicated()]

Empty DataFrame
Columns: [transaction_id, timestamp, customer_id, product_id, quantity, discount_applied, gross_revenue, campaign_id, refund_flag]
Index: []

In [76]:
transactions = transactions.dropna(subset=['product_id'])

In [77]:
transactions['gross_revenue'] = transactions['gross_revenue'].fillna(0)

In [78]:
transactions['product_id'] = transactions['product_id'].astype(int)
transactions['campaign_id'] = transactions['campaign_id'].astype(int)

In [79]:
transactions[transactions.duplicated()]

Empty DataFrame
Columns: [transaction_id, timestamp, customer_id, product_id, quantity, discount_applied, gross_revenue, campaign_id, refund_flag]
Index: []

In [80]:
transactions['net_revenue'] = transactions['gross_revenue'] - transactions['discount_applied']
transactions['revenue_per_item'] = transactions['gross_revenue'] / transactions['quantity']

In [81]:
events.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,39686.0,11/10/2022 8:07,1.0,112261.0,click,1615.0,mobile,Social,14.0,PDP,85.9,Control
1,42433.0,5/20/2023 0:31,1.0,634043.0,view,586.0,mobile,Paid Search,46.0,PLP,183.4,Control
2,94194.0,12/7/2021 7:04,1.0,272927.0,click,909.0,tablet,Paid Search,47.0,PLP,289.1,Variant_A
3,178199.0,4/7/2023 22:31,1.0,79635.0,click,1577.0,tablet,Organic,0.0,PLP,225.0,Control
4,335889.0,6/13/2021 12:35,1.0,5155.0,view,1890.0,mobile,Organic,0.0,PLP,179.4,Variant_B

In [82]:
events.info()
events.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   event_id              538727 non-null  float64
 1   timestamp             538727 non-null  object
 2   customer_id           538727 non-null  float64
 3   session_id            538727 non-null  float64
 4   event_type            538727 non-null  object
 5   product_id            484693 non-null  float64
 6   device_type           527933 non-null  object
 7   traffic_source        538727 non-null  object
 8   campaign_id           538727 non-null  float64
 9   page_category         538727 non-null  object
 10  session_duration_sec  538727 non-null  float64
 11  experiment_group      538727 non-null  object
dtypes: float64(6), object(6)
memory usage: 96.0+ MB

event_id                509848
timestamp               509848
customer_id             509848
session_id              509848
event_type              509848
product_id              563882
device_type             520642
traffic_source          509848
campaign_id             509848
page_category           509848
session_duration_sec    509848
experiment_group        509848
dtype: int64

In [83]:
events[events.duplicated()]

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
538728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538732,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [84]:
events = events.dropna()

In [85]:
events[events.duplicated()]

Empty DataFrame
Columns: [event_id, timestamp, customer_id, session_id, event_type, product_id, device_type, traffic_source, campaign_id, page_category, session_duration_sec, experiment_group]
Index: []

In [86]:
events['timestamp'] = pd.to_datetime(events['timestamp'])

In [87]:
events['event_type'] = events['event_type'].str.strip().str.lower()
events['traffic_source'] = events['traffic_source'].str.strip().str.title()
events['device_type'] = events['device_type'].str.strip().str.title()
events['experiment_group'] = events['experiment_group'].str.strip().str.title()
events['page_category'] = events['page_category'].str.strip().str.lower()

In [88]:
events['product_id'] = events['product_id'].fillna(0)

In [89]:
events['device_type'] = events['device_type'].fillna("Unknown")

In [90]:
events['product_id'] = events['product_id'].astype(int)
events['campaign_id'] = events['campaign_id'].astype(int)

In [91]:
events['is_purchase'] = (events['event_type'] == 'purchase').astype(int)

In [92]:
events['hour'] = events['timestamp'].dt.hour
events['day'] = events['timestamp'].dt.day_name()

In [93]:
events['event_type'].value_counts()

event_type
view           275794
click           99958
add_to_cart     74729
purchase        24456
Name: count, dtype: int64

In [94]:
events.groupby('experiment_group')['is_purchase'].mean()
events.groupby('device_type')['is_purchase'].mean()

device_type
Desktop    0.051942
Mobile     0.051206
Tablet     0.051788
Name: is_purchase, dtype: float64

In [95]:
events.groupby('experiment_group')['is_purchase'].mean()

experiment_group
Control      0.047887
Variant_A    0.051638
Variant_B    0.062118
Name: is_purchase, dtype: float64

In [96]:
events.to_csv("../Clean_Data/events.csv", index=False)
transactions.to_csv("../Clean_Data/transactions.csv", index=False)
customers.to_csv("../Clean_Data/customers.csv", index=False)
products.to_csv("../Clean_Data/products.csv" , index=False)
campaigns.to_csv("../Clean_Data/campaigns.csv", index=False)