In [14]:
import pandas as pd
events=pd.read_csv("../RAW_DATA/event.csv")
customers=pd.read_csv("../RAW_DATA/customers.csv")
products=pd.read_csv("../RAW_DATA/products.csv")
transactions=pd.read_csv("../RAW_DATA/transactions.csv")
campaigns=pd.read_csv("../RAW_DATA/campaigns.csv")

In [23]:
customers.head()

,customer_id,signup_date,country,age,gender,loyalty_tier,acquisition_channel
0,1,2021-04-08,BR,48,Male,Bronze,Referral
1,2,2023-04-28,IN,36,Female,Silver,Organic
2,3,2022-12-18,UK,35,Female,Silver,Organic
3,4,2022-04-26,US,45,Male,Silver,Paid Search
4,5,2022-04-20,IN,53,Male,Silver,Organic

In [25]:
customers.info()
customers.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          100000 non-null  int64
 1   signup_date          100000 non-null  object
 2   country              100000 non-null  object
 3   age                  100000 non-null  int64
 4   gender               100000 non-null  object
 5   loyalty_tier         100000 non-null  object
 6   acquisition_channel  100000 non-null  object
dtypes: int64(2), object(5)
memory usage: 5.3+ MB

customer_id            0
signup_date            0
country                0
age                    0
gender                 0
loyalty_tier           0
acquisition_channel    0
dtype: int64

In [15]:
customers = customers.drop_duplicates()

In [19]:
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [17]:
products.head()

   product_id     category     brand  base_price launch_date  is_premium
0           1      Grocery  Brand_58       14.19  2021-08-02           0
1           2      Fashion   Brand_1       25.80  2021-09-14           0
2           3  Electronics  Brand_70      165.46  2021-01-18           1
3           4      Fashion  Brand_56       75.45  2023-03-03           1
4           5       Sports   Brand_1       72.50  2022-04-19           1

In [20]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product_id   2000 non-null   int64
 1   category     2000 non-null   object
 2   brand        2000 non-null   object
 3   base_price   2000 non-null   float64
 4   launch_date  2000 non-null   object
 5   is_premium   2000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 93.9+ KB

In [21]:
products.isnull().sum()

product_id     0
category       0
brand          0
base_price     0
launch_date    0
is_premium     0
dtype: int64

In [22]:
products[products.duplicated()]

Empty DataFrame
Columns: [product_id, category, brand, base_price, launch_date, is_premium]
Index: []

In [23]:
products['launch_date']=pd.to_datetime(products['launch_date'])

In [24]:
campaigns.head()

,campaign_id,channel,objective,start_date,end_date,target_segment,expected_uplift
0,1,Paid Search,Cross-sell,2021-10-25,2021-11-26,Deal Seekers,0.022
1,2,Email,Retention,2021-10-24,2021-12-24,Deal Seekers,0.116
2,3,Email,Reactivation,2023-10-08,2023-11-30,Churn Risk,0.100
3,4,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111
4,5,Social,Acquisition,2022-07-09,2022-09-29,New Customers,0.144

In [25]:
campaigns.info()
campaigns.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   campaign_id      50 non-null     int64
 1   channel          50 non-null     object
 2   objective        50 non-null     object
 3   start_date       50 non-null     object
 4   end_date         50 non-null     object
 5   target_segment   50 non-null     object
 6   expected_uplift  50 non-null     float64
dtypes: float64(1), int64(1), object(5)
memory usage: 2.9+ KB

campaign_id        0
channel            0
objective          0
start_date         0
end_date           0
target_segment     0
expected_uplift    0
dtype: int64

In [26]:
campaigns[campaigns.duplicated()]

Empty DataFrame
Columns: [campaign_id, channel, objective, start_date, end_date, target_segment, expected_uplift]
Index: []

In [27]:
campaigns['start_date']=pd.to_datetime(campaigns['start_date'])
campaigns['end_date']=pd.to_datetime(campaigns['end_date'])

In [28]:
campaigns['campaign_duration_days'] = (
    campaigns['end_date'] - campaigns['start_date']
).dt.days

In [29]:
transactions.head()

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.00,43.74,0,0
1,2,2023-06-06 21:14:26,54871,1901.0,3,0.00,174.78,21,0
2,3,2023-08-31 05:29:54,51818,1884.0,1,0.00,40.61,37,0
3,4,2022-06-26 20:33:46,18164,1114.0,2,0.15,68.76,13,0
4,5,2023-07-26 18:12:35,86915,408.0,1,0.00,14.64,4,0

In [30]:
transactions.info()
transactions.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103127 entries, 0 to 103126
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    103127 non-null  int64
 1   timestamp         103127 non-null  object
 2   customer_id       103127 non-null  int64
 3   product_id        92678 non-null   float64
 4   quantity          103127 non-null  int64
 5   discount_applied  103127 non-null  float64
 6   gross_revenue     92678 non-null   float64
 7   campaign_id       103127 non-null  int64
 8   refund_flag       103127 non-null  int64
dtypes: float64(3), int64(5), object(1)
memory usage: 7.1+ MB

transaction_id          0
timestamp               0
customer_id             0
product_id          10449
quantity                0
discount_applied        0
gross_revenue       10449
campaign_id             0
refund_flag             0
dtype: int64

In [31]:
transactions['timestamp']=pd.to_datetime(transactions['timestamp'])

In [32]:
transactions = transactions.dropna(subset=['product_id'])

In [33]:
transactions = transactions.dropna(subset=['product_id'])

In [34]:
transactions['gross_revenue'] = transactions['gross_revenue'].fillna(0)

In [35]:
transactions['product_id'] = transactions['product_id'].astype(int)
transactions['campaign_id'] = transactions['campaign_id'].astype(int)

In [36]:
transactions[transactions.duplicated()]

Empty DataFrame
Columns: [transaction_id, timestamp, customer_id, product_id, quantity, discount_applied, gross_revenue, campaign_id, refund_flag]
Index: []

In [37]:
transactions['net_revenue'] = transactions['gross_revenue'] - transactions['discount_applied']
transactions['revenue_per_item'] = transactions['gross_revenue'] / transactions['quantity']

In [38]:
events.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,14-01-2021 13:35,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,03-12-2021 21:36,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,27-12-2021 08:25,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,22-01-2022 15:06,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,10-05-2021 12:03,92735,60646,bounce,NaN,desktop,Email,26,PLP,53.1,Variant_A

In [39]:
events.info()
events.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 509011 entries, 0 to 509010
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   event_id              509011 non-null  int64
 1   timestamp             509011 non-null  object
 2   customer_id           509011 non-null  int64
 3   session_id            509011 non-null  int64
 4   event_type            509011 non-null  object
 5   product_id            458396 non-null  float64
 6   device_type           498616 non-null  object
 7   traffic_source        509011 non-null  object
 8   campaign_id           509011 non-null  int64
 9   page_category         509011 non-null  object
 10  session_duration_sec  509011 non-null  float64
 11  experiment_group      509011 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 46.6+ MB

event_id                    0
timestamp                   0
customer_id                 0
session_id                  0
event_type                  0
product_id              50615
device_type             10395
traffic_source              0
campaign_id                 0
page_category               0
session_duration_sec        0
experiment_group            0
dtype: int64

In [40]:
events[events.duplicated()]

Empty DataFrame
Columns: [event_id, timestamp, customer_id, session_id, event_type, product_id, device_type, traffic_source, campaign_id, page_category, session_duration_sec, experiment_group]
Index: []

In [41]:
events['timestamp'] = pd.to_datetime(events['timestamp'])

C:\Users\acer\AppData\Local\Temp\ipykernel_9360\3353340585.py:1: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  events['timestamp'] = pd.to_datetime(events['timestamp'])

In [42]:
events['event_type'] = events['event_type'].str.strip().str.lower()
events['traffic_source'] = events['traffic_source'].str.strip().str.title()
events['device_type'] = events['device_type'].str.strip().str.title()
events['experiment_group'] = events['experiment_group'].str.strip().str.title()
events['page_category'] = events['page_category'].str.strip().str.lower()

In [43]:
events['product_id'] = events['product_id'].fillna(0)

In [44]:
events['device_type'] = events['device_type'].fillna("Unknown")

In [45]:
events['product_id'] = events['product_id'].astype(int)
events['campaign_id'] = events['campaign_id'].astype(int)

In [46]:
events['is_purchase'] = (events['event_type'] == 'purchase').astype(int)

In [47]:
events['hour'] = events['timestamp'].dt.hour
events['day'] = events['timestamp'].dt.day_name()

In [48]:
events['event_type'].value_counts()

event_type
view           265767
click           96582
add_to_cart     72464
bounce          47983
purchase        26215
Name: count, dtype: int64

In [49]:
events.groupby('experiment_group')['is_purchase'].mean()
events.groupby('device_type')['is_purchase'].mean()

device_type
Desktop    0.051514
Mobile     0.051479
Tablet     0.051741
Unknown    0.051371
Name: is_purchase, dtype: float64

In [50]:
events.groupby('experiment_group')['is_purchase'].mean()

experiment_group
Control      0.047628
Variant_A    0.052568
Variant_B    0.061978
Name: is_purchase, dtype: float64

In [51]:
events.to_csv("../Clean_Data/events", index=False)
transactions.to_csv("../Clean_Data/transactions", index=False)
customers.to_csv("../Clean_Data/customers", index=False)
products.to_csv("../Clean_Data/products" , index=False)
campaigns.to_csv("../Clean_Data/campaigns", index=False)